### ISSUE TITLE
15/6

### ISSUE THREAD

**Issue by TM11153431** [smeber/Programmeerproject#1]
Sanne,

Alles staat in de map code, wat niet superduidelijk is, dit zou ik nog verbeteren. Je processbook heeft de verkeerde naam, het zou PROCESS.MD moeten zijn. 

Qua committen heb je alleen 7 juni gemist

Tim

**Comment by smeber** [comment]
Hai Tim,

Ik zie dit nu pas!
Waar is het dan handig om al m'n code te hebben staan? Gewoon los lijkt mij juist heel onoverzichtelijk, toch? En is het erg dat ik op 7 juni niks heb gecommit? Dat was het begin van het vak, dus denk dat ik daar toen nog niet helemaal scherp op was..

Groetjes!

**Comment by smeber** [comment]
Gedaan!

**Comment by smeber** [comment]
Gelukt!
